[package]
name = "picante"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors = ["Amos Wenger <amos@bearcove.eu>"]
description = "An async incremental query runtime"
repository = "https://github.com/bearcove/picante"
homepage = "https://github.com/bearcove/picante"

[dependencies]
dashmap.workspace = true
facet.workspace = true
facet-postcard.workspace = true
futures.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
